all: creating_README.md

creating_README.md:
	touch README.md
	echo "PROJECT TITLE: Peer-graded assignment: Bash, Make, Git and Github /n/n" > README.md
	echo "COURSERA - THE UNIX WORKBENCH\n" >> README.md
	echo "Make ran on :" >> README.md
	date >> README.md
	echo "\n Number of lines in sh file is:" >> README.md
	cat guessinggame.sh | wc -l >> README.md
